In [1]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 48.0 MB/s  0:00:006m0:00:01
Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 46.0 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.6 pandas-3.0.3

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

In [7]:
df = pd.DataFrame(
    {
        "이름": ['강은수', '조재영', '이한솔', '뽀로로'],
        "학과": ['언어학', '국문학', '언어학', '역사학'],
        "학년": [2, 3, 1, 4],
        "국어": [88, 72, 95, 60],
        "수학": [75, 88, 82, 50],
        "영어": [90, 79, 85, 70]
    }
)
print(df)

    이름   학과  학년  국어  수학  영어
0  강은수  언어학   2  88  75  90
1  조재영  국문학   3  72  88  79
2  이한솔  언어학   1  95  82  85
3  뽀로로  역사학   4  60  50  70

In [ ]:
print(df.shape)
print(df.columns)
print(df.index)
print(df.dtypes)

(4, 6)
Index(['이름', '학과', '학년', '국어', '수학', '영어'], dtype='str')
RangeIndex(start=0, stop=4, step=1)

In [10]:
print(df.head(2))
print(df.tail(2))

    이름   학과  학년  국어  수학  영어
0  강은수  언어학   2  88  75  90
1  조재영  국문학   3  72  88  79
    이름   학과  학년  국어  수학  영어
2  이한솔  언어학   1  95  82  85
3  뽀로로  역사학   4  60  50  70

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      4 non-null      str
 1   학과      4 non-null      str
 2   학년      4 non-null      int64
 3   국어      4 non-null      int64
 4   수학      4 non-null      int64
 5   영어      4 non-null      int64
dtypes: int64(4), str(2)
memory usage: 324.0 bytes

In [12]:
df.describe()

             학년         국어         수학         영어
count  4.000000   4.000000   4.000000   4.000000
mean   2.500000  78.750000  73.750000  81.000000
std    1.290994  15.777093  16.700798   8.602325
min    1.000000  60.000000  50.000000  70.000000
25%    1.750000  69.000000  68.750000  76.750000
50%    2.500000  80.000000  78.500000  82.000000
75%    3.250000  89.750000  83.500000  86.250000
max    4.000000  95.000000  88.000000  90.000000

In [13]:
df2 = df.set_index('이름')
df2

      학과  학년  국어  수학  영어
이름
강은수  언어학   2  88  75  90
조재영  국문학   3  72  88  79
이한솔  언어학   1  95  82  85
뽀로로  역사학   4  60  50  70

In [14]:
df2.info()

<class 'pandas.DataFrame'>
Index: 4 entries, 강은수 to 뽀로로
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학과      4 non-null      str
 1   학년      4 non-null      int64
 2   국어      4 non-null      int64
 3   수학      4 non-null      int64
 4   영어      4 non-null      int64
dtypes: int64(4), str(1)
memory usage: 192.0+ bytes

In [17]:
df2.loc['이한솔','국어']
df2.loc[:,'국어']
df2.loc['강은수':'이한솔','국어']

이름
강은수    88
조재영    72
이한솔    95
Name: 국어, dtype: int64

In [19]:
df2.iloc[2, 2]
df2.iloc[0:2, 2]

이름
강은수    88
조재영    72
Name: 국어, dtype: int64

In [22]:
df['국어']
df['국어'] >= 80
df[df['국어']>= 80]

    이름   학과  학년  국어  수학  영어
0  강은수  언어학   2  88  75  90
2  이한솔  언어학   1  95  82  85

In [25]:
df['학과'] == '언어학'
df['학과'].str.contains('언어학')
df['학과'].str.contains('언어학') & (df['학년']>= 2)

0     True
1    False
2    False
3    False
dtype: bool

In [26]:
df.loc[df['수학']<70, ['이름', '수학']]

    이름  수학
3  뽀로로  50

In [ ]:
import numpy as np

df = pd.DataFrame({
    '이름': ['강은수', '조재영', '이한솔', '뽀로로'],
    '국어': [88, np.nan, 95, 60],
    '수학': [70, 85, np.nan, 50],
    '영어': [90, 79, 85, np.nan]
})

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      4 non-null      str
 1   국어      3 non-null      float64
 2   수학      3 non-null      float64
 3   영어      3 non-null      float64
dtypes: float64(3), str(1)
memory usage: 260.0 bytes

In [32]:
print(df.isna().sum())
print(df.isna().sum().sum())

이름    0
국어    1
수학    1
영어    1
dtype: int64
3

In [34]:
df.dropna()
df.dropna(subset=['국어'])

    이름    국어    수학    영어
0  강은수  88.0  70.0  90.0
2  이한솔  95.0   NaN  85.0
3  뽀로로  60.0  50.0   NaN

In [35]:
df.fillna(0)

    이름    국어    수학    영어
0  강은수  88.0  70.0  90.0
1  조재영   0.0  85.0  79.0
2  이한솔  95.0   0.0  85.0
3  뽀로로  60.0  50.0   0.0

In [36]:
means = df[['국어', '수학', '영어']].mean()
means

국어    81.000000
수학    68.333333
영어    84.666667
dtype: float64

In [37]:
df.fillna(means)

    이름    국어         수학         영어
0  강은수  88.0  70.000000  90.000000
1  조재영  81.0  85.000000  79.000000
2  이한솔  95.0  68.333333  85.000000
3  뽀로로  60.0  50.000000  84.666667

In [38]:
df = pd.DataFrame(
    {
        "이름": ['강은수', '조재영', '이한솔', '뽀로로'],
        "학과": ['언어학', '국문학', '언어학', '역사학'],
        "학년": [2, 3, 1, 4],
        "국어": [88, 72, 95, 60],
        "수학": [75, 88, 82, 50],
        "영어": [90, 79, 85, 70]
    }
)

print(df)

    이름   학과  학년  국어  수학  영어
0  강은수  언어학   2  88  75  90
1  조재영  국문학   3  72  88  79
2  이한솔  언어학   1  95  82  85
3  뽀로로  역사학   4  60  50  70

In [40]:
df['평균'] = (df['국어'] + df['수학'] + df['영어']) / 3
df

    이름   학과  학년  국어  수학  영어         평균
0  강은수  언어학   2  88  75  90  84.333333
1  조재영  국문학   3  72  88  79  79.666667
2  이한솔  언어학   1  95  82  85  87.333333
3  뽀로로  역사학   4  60  50  70  60.000000

In [44]:
df['합격'] = df['평균'] >= 70
df

    이름   학과  학년  국어  수학  영어         평균     합격
0  강은수  언어학   2  88  75  90  84.333333   True
1  조재영  국문학   3  72  88  79  79.666667   True
2  이한솔  언어학   1  95  82  85  87.333333   True
3  뽀로로  역사학   4  60  50  70  60.000000  False

In [46]:
def grade(score:int) -> str:
    if score >= 90:
        return 'A'
    if score >= 80:
        return 'B'
    if score >= 70:
        return 'C'
    if score >= 60:
        return 'D'
    return 'F'

df['등급'] = df['국어'].apply(grade)
df

    이름   학과  학년  국어  수학  영어         평균     합격 등급
0  강은수  언어학   2  88  75  90  84.333333   True  B
1  조재영  국문학   3  72  88  79  79.666667   True  C
2  이한솔  언어학   1  95  82  85  87.333333   True  A
3  뽀로로  역사학   4  60  50  70  60.000000  False  D

In [48]:
df.sort_values('평균', ascending=False)

    이름   학과  학년  국어  수학  영어         평균     합격 등급
2  이한솔  언어학   1  95  82  85  87.333333   True  A
0  강은수  언어학   2  88  75  90  84.333333   True  B
1  조재영  국문학   3  72  88  79  79.666667   True  C
3  뽀로로  역사학   4  60  50  70  60.000000  False  D

In [ ]:
df.groupby('학과')['국어'].mean()

학과
국문학    72.0
언어학    91.5
역사학    60.0
Name: 국어, dtype: float64